/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/co-reading/': RouteRecordInfo<'/co-reading/', '/co-reading', Record<never, never>, Record<never, never>>,
    '/co-reading/ni/': RouteRecordInfo<'/co-reading/ni/', '/co-reading/ni', Record<never, never>, Record<never, never>>,
    '/co-reading/taze/': RouteRecordInfo<'/co-reading/taze/', '/co-reading/taze', Record<never, never>, Record<never, never>>,
    '/co-reading/vueuse/': RouteRecordInfo<'/co-reading/vueuse/', '/co-reading/vueuse', Record<never, never>, Record<never, never>>,
    '/leetcode/': RouteRecordInfo<'/leetcode/', '/leetcode', Record<never, never>, Record<never, never>>,
    '/leetcode/simple/': RouteRecordInfo<'/leetcode/simple/', '/leetcode/simple', Record<never, never>, Record<never, never>>,
    '/leetcode/simple/longest-common-prefix': RouteRecordInfo<'/leetcode/simple/longest-common-prefix', '/leetcode/simple/longest-common-prefix', Record<never, never>, Record<never, never>>,
    '/leetcode/simple/palindrome-number': RouteRecordInfo<'/leetcode/simple/palindrome-number', '/leetcode/simple/palindrome-number', Record<never, never>, Record<never, never>>,
    '/leetcode/simple/roman-to-integer': RouteRecordInfo<'/leetcode/simple/roman-to-integer', '/leetcode/simple/roman-to-integer', Record<never, never>, Record<never, never>>,
    '/leetcode/simple/sum-of-two-numbers': RouteRecordInfo<'/leetcode/simple/sum-of-two-numbers', '/leetcode/simple/sum-of-two-numbers', Record<never, never>, Record<never, never>>,
    '/leetcode/simple/valid-parentheses': RouteRecordInfo<'/leetcode/simple/valid-parentheses', '/leetcode/simple/valid-parentheses', Record<never, never>, Record<never, never>>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/notes/combining-jsdoc-with-typeScript': RouteRecordInfo<'/notes/combining-jsdoc-with-typeScript', '/notes/combining-jsdoc-with-typeScript', Record<never, never>, Record<never, never>>,
    '/notes/deep-understanding-of-TDD': RouteRecordInfo<'/notes/deep-understanding-of-TDD', '/notes/deep-understanding-of-TDD', Record<never, never>, Record<never, never>>,
    '/notes/design-documentation': RouteRecordInfo<'/notes/design-documentation', '/notes/design-documentation', Record<never, never>, Record<never, never>>,
    '/notes/design-documentation-min': RouteRecordInfo<'/notes/design-documentation-min', '/notes/design-documentation-min', Record<never, never>, Record<never, never>>,
    '/notes/first-time-customized-keyboard': RouteRecordInfo<'/notes/first-time-customized-keyboard', '/notes/first-time-customized-keyboard', Record<never, never>, Record<never, never>>,
    '/notes/how-to-ask-the-right-question': RouteRecordInfo<'/notes/how-to-ask-the-right-question', '/notes/how-to-ask-the-right-question', Record<never, never>, Record<never, never>>,
    '/notes/make-and-makefile': RouteRecordInfo<'/notes/make-and-makefile', '/notes/make-and-makefile', Record<never, never>, Record<never, never>>,
    '/notes/npm-semantic-version': RouteRecordInfo<'/notes/npm-semantic-version', '/notes/npm-semantic-version', Record<never, never>, Record<never, never>>,
    '/notes/poetic-bonds-in-the-digital-age': RouteRecordInfo<'/notes/poetic-bonds-in-the-digital-age', '/notes/poetic-bonds-in-the-digital-age', Record<never, never>, Record<never, never>>,
    '/notes/rss-getting-started-guide': RouteRecordInfo<'/notes/rss-getting-started-guide', '/notes/rss-getting-started-guide', Record<never, never>, Record<never, never>>,
    '/notes/talk-about-npm-shrinkwrap': RouteRecordInfo<'/notes/talk-about-npm-shrinkwrap', '/notes/talk-about-npm-shrinkwrap', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/flow': RouteRecordInfo<'/posts/flow', '/posts/flow', Record<never, never>, Record<never, never>>,
  }
}
